### ISSUE TITLE
First Start of Script

### ISSUE THREAD

**Issue by Kunstnebel** [lee8oi/hexperience#1]
With the first start, the script cant set the variable (GM_setValue(dbName, "{}");) so the user receive a error (unexpected u) that means empty json scring.

fix: 

function loadIpLogs(dbName) {
   if (GM_getValue(dbName) == "") {
       GM_setValue(dbName, "{}");
   }
    var text = GM_getValue(dbName);
    var db = JSON.parse(text);
    var getBtns = function (i) {

**Comment by lee8oi** [comment]
Added fix to latest version of script.
