### ISSUE TITLE
Third & fourth Request

### ISSUE THREAD

**Issue by pyzro** [lee8oi/hexperience#11]
-- A button to clear each IP database.
-- Some way to tell which IP address in the local IP database to see if someone logged into you. Currently, it just combines who you've logged into and who's logged into you in one list.

I wish I could contribute more than just requests. So far I've disabled two other scripts because yours just works better.

**Comment by lee8oi** [comment]
I just got out of the hospital so I'll need some time. But I promise I'll look into these. I know the script needs some bug fixes and improvements.

**Comment by pyzro** [comment]
Not a problem, take your time. I've been seeing if I can modify the script, but I've been failing... miserably.

Hope you're feeling better.

**Comment by lee8oi** [comment]
Thanks. P.S. Nothing wrong with trying. That's how you learn. You can even start with smaller scripts and figure em out. Do stuff with them. That's a good way to sharpen up your skills. Studying up on JS, jQuery, and UserScripts can help a lot with understanding this script.

**Comment by lee8oi** [comment]
Ok a 'wipe' button has been added. Works for each DB individually. The problem with the local ip database has been fixed. Closing this issue. Report a new one if you have a problems.
