### ISSUE TITLE
'Log Monitor' - Not Working

### ISSUE THREAD

**Issue by Nullus0x** [lee8oi/hexperience#12]
This feature doesn't seem to work, it refreshes the page, but whenever you click on 'Stop' it just loads a blank log.

**Comment by lee8oi** [comment]
I've been noticing this too. Though I don't get enough incoming hacks to really test it out. But I'll look into it when I can. Still in recovery right now.

**Comment by lee8oi** [comment]
I took a quick look and found the problem. Should be fixed now. Posting new version of script.
