### ISSUE TITLE
How can i use this?

### ISSUE THREAD

**Issue by biosdaddy1** [lee8oi/hexperience#15]
Hello. First of all thanks for this amazing share but i couldn't find how can i use this. Could you explain please?

**Comment by lee8oi** [comment]
I wrote it for Tampermonkey. Install that in your browser then you can
install the script. From there Tampermonkey should detect when you are on
the Hacker Experience site and the script features should enable. But I
haven't tested things in a while and I know the game is ending at some
point to make way for the new version. So good luck.

**Comment by biosdaddy1** [comment]
Thank you so much.
