### ISSUE TITLE
refix of my last Issue

### ISSUE THREAD

**Issue by Kunstnebel** [lee8oi/hexperience#2]
if (GM_getValue(dbName) == "") {
        GM_setValue(dbName, "{}");
    }
to
 if (!GM_getValue(dbName) ) {
        GM_setValue(dbName, "{}");
    }

**Comment by lee8oi** [comment]
So basically we're reverting to the way the code was before I added your fix.

**Comment by lee8oi** [comment]
I think you need to look at the code that's available and not the code you are using when you decide to report a fix.

**Comment by Kunstnebel** [comment]
I know the Problem... You did a json decode of the value Text and if the
value is empty will it result in JS error codes. So first check the value
and set a json Text.

Like now, this will work fine.

Gesendet von meinem Smartphone
Am 22.12.2015 02:50 schrieb "Lee Forest" notifications@github.com:

**Comment by lee8oi** [comment]
Fix has been added in 0.8.2. If you are correct, this should be the end of this issue. But I did use a similar fix previously. Lets hope we finally have a solution. Thank you for your time. I'll keep an open mind of anything else you might notice. Just be aware of the current version of the code available. That's all I ask.

**Comment by Kunstnebel** [comment]
>
> var links = document.getElementsByClassName('list-ip');
> var user = document.getElementsByClassName('list-user');
> var i;
> for (i = 0; i < links.length; ++i) {
>     links[i].getElementsByTagName('a')[0].href =
> links[i].getElementsByTagName('a')[0].href +
> "&action=login&user=root&pass=" +
> user[i].getElementsByTagName('span')[3].innerHTML;
>     links[i].getElementsByTagName('a')[0].target = "_blank";
> }



this Snippet replace the hacked DB IP´s to login directly to the hacked
servers. its very useful for me.

Peter Vondracek
---



2015-12-22 8:23 GMT+01:00 Lee Forest <notifications@github.com>:
