### ISSUE TITLE
Idea - Snippet - Direct Login to hacked Servers

### ISSUE THREAD

**Issue by Kunstnebel** [lee8oi/hexperience#3]
var links = document.getElementsByClassName('list-ip');
var user = document.getElementsByClassName('list-user');
var i;
for (i = 0; i < links.length; ++i) {
    links[i].getElementsByTagName('a')[0].href = links[i].getElementsByTagName('a')[0].href + "&action=login&user=root&pass=" + user[i].getElementsByTagName('span')[3].innerHTML;
    links[i].getElementsByTagName('a')[0].target = "_blank";
}

**Comment by lee8oi** [comment]
For consistency I'll look into creating a jquery version of this soon and
adding it. Thanks for the idea.

**Comment by lee8oi** [comment]
Added 'login' link to Hacked Database. Version bumped to 0.8.3.
