### ISSUE TITLE
Auto hide

### ISSUE THREAD

**Issue by vorticalbox** [lee8oi/hexperience#6]
Auto hide no longer works.

**Comment by lee8oi** [comment]
Been a while since I played the game or worked on this script. But I'll see what I can do. Thanks for the report.

**Comment by lee8oi** [comment]
New fixes in place that should resolve this issue.

**Comment by lee8oi** [comment]
Reopening this issue until problem is confirmed to be resolved.

**Comment by lee8oi** [comment]
Auto hideme is working for me. So I'm closing this issue for good now. If you have further problems open a new issue.
